#Settings, for total application

defaults: &defaults
 active: Active
 inactive: InActive
 yesValue: 0
 noValue: 1
 inotVerify: 2
 admin_role: admin
 project_member_role: projectMember
 guest_role: guest
# development environment
development:
 <<: *defaults
 
# test enviroment
test:
 <<: *defaults
 
# staging environment 
staging:
 <<: *defaults 
 
# production environment
production:
 <<: *defaults