#Settings, for total application

defaults: &defaults
 active: Active
 inactive: InActive
 yesValue: 0
 noValue: 1
 inotVerify: 2
# development environment
development:
 <<: *defaults
 
# test enviroment
test:
 <<: *defaults
 
# production environment
production:
 <<: *defaults